name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      db:
        image: postgres:12
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        options: >-
          --health-cmd "pg_isready -U user -d mydb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5          

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r customer_management_api/requirements.txt
    # - name: Run Tests
    #   run: |
    #     python customer_management_api/manage.py test customers

    - name: Run tests with coverage
      run: |
        coverage run --source="." customer_management_api/manage.py test customers
        coverage report
        coverage html        
